# Generated by Django 5.2.8 on 2025-12-01 00:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del comercio/empresa cliente', max_length=255)),
                ('rut', models.CharField(help_text='RUT de la empresa (sin puntos ni guion)', max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Dirección registrada de la empresa', null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la empresa puede usar la plataforma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin (TemucoSoft)'), ('admin_cliente', 'Admin Cliente (Dueño)'), ('gerente', 'Gerente'), ('vendedor', 'Vendedor'), ('cliente_final', 'Cliente Final (E-commerce)')], default='cliente_final', help_text='Rol del usuario en el sistema', max_length=20)),
                ('rut', models.CharField(blank=True, help_text='RUT chileno sin puntos ni guion (ej: 123456789)', max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(9)])),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el usuario puede acceder al sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, help_text='Empresa/tenant a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='catalyst_app.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la sucursal', max_length=255)),
                ('address', models.TextField(help_text='Dirección de la sucursal')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la sucursal está operativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, help_text='Gerente responsable de la sucursal', limit_choices_to={'role': 'gerente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(help_text='Empresa propietaria de la sucursal', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='catalyst_app.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, help_text='Cantidad actual de stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_point', models.IntegerField(default=10, help_text='Cantidad mínima antes de hacer reorden', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_counted', models.DateTimeField(auto_now=True, help_text='Última vez que se contabilizó el stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalyst_app.branch')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada (Compra a Proveedor)'), ('salida', 'Salida (Venta)'), ('ajuste', 'Ajuste'), ('devolucion', 'Devolución')], help_text='Tipo de movimiento', max_length=20)),
                ('quantity', models.IntegerField(help_text='Cantidad movida', validators=[django.core.validators.MinValueValidator(1)])),
                ('reference', models.CharField(blank=True, help_text='Referencia (Nº de compra, venta, etc.)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales del movimiento', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalyst_app.inventory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Número de orden único', max_length=50, unique=True)),
                ('customer_name', models.CharField(help_text='Nombre del cliente', max_length=255)),
                ('customer_email', models.EmailField(help_text='Email del cliente', max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_rut', models.CharField(blank=True, help_text='RUT del cliente (opcional)', max_length=12, null=True)),
                ('shipping_address', models.TextField(help_text='Dirección de envío')),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal sin impuestos', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax', models.DecimalField(decimal_places=2, default=0, help_text='Impuestos (IVA)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costo de envío', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, help_text='Total de la orden', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('preparando', 'Preparando'), ('enviada', 'Enviada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('payment_status', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('reembolso', 'Reembolso')], default='pendiente', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales de la orden', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Tienda que recibe la orden', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='catalyst_app.company')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario autenticado (opcional para e-commerce anónimo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Código único del producto', max_length=100)),
                ('name', models.CharField(help_text='Nombre del producto', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del producto', null=True)),
                ('category', models.CharField(help_text='Categoría del producto', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio de venta', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.DecimalField(decimal_places=2, help_text='Costo del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el producto está disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Empresa propietaria del producto', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalyst_app.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Cantidad solicitada', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento de la orden', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal del item', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalyst_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalyst_app.product')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalyst_app.product'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Número de factura del proveedor', max_length=100)),
                ('purchase_date', models.DateField(help_text='Fecha de la compra')),
                ('delivery_date', models.DateField(blank=True, help_text='Fecha de entrega/recepción', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Monto total de la compra', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcialmente_pagado', 'Parcialmente Pagado')], default='pendiente', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre la compra', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(help_text='Sucursal que recibe la compra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='catalyst_app.branch')),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Cantidad comprada', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario de compra', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal del item (cantidad x precio)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalyst_app.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalyst_app.purchase')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='Número de comprobante/boleta', max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, help_text='Nombre del cliente (opcional)', max_length=255, null=True)),
                ('customer_rut', models.CharField(blank=True, help_text='RUT del cliente (opcional)', max_length=12, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal sin impuestos', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax', models.DecimalField(decimal_places=2, default=0, help_text='Impuestos (IVA)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, help_text='Total de la venta', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta Débito'), ('tarjeta_credito', 'Tarjeta Crédito'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('otro', 'Otro')], help_text='Método de pago utilizado', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Referencia del pago (nº transacción, cheque, etc.)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales de la venta', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la venta')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(help_text='Sucursal donde se realiza la venta', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='catalyst_app.branch')),
                ('seller', models.ForeignKey(help_text='Vendedor que realiza la venta', limit_choices_to={'role': 'vendedor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta Débito'), ('tarjeta_credito', 'Tarjeta Crédito'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('otro', 'Otro')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Referencia de pago (nº transacción, etc.)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='catalyst_app.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Cantidad vendida', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento de la venta', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal del item', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalyst_app.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalyst_app.sale')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Session key para usuarios anónimos', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Tienda del carro', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_carts', to='catalyst_app.company')),
                ('user', models.OneToOneField(blank=True, help_text='Usuario autenticado (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Cantidad en el carro', validators=[django.core.validators.MinValueValidator(1)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalyst_app.product')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalyst_app.shoppingcart')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('basico', 'Plan Básico'), ('estandar', 'Plan Estándar'), ('premium', 'Plan Premium')], help_text='Plan contratado', max_length=20)),
                ('start_date', models.DateField(help_text='Fecha de inicio de la suscripción')),
                ('end_date', models.DateField(help_text='Fecha de término de la suscripción')),
                ('active', models.BooleanField(default=True, help_text='Indica si la suscripción está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='catalyst_app.company')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del proveedor', max_length=255)),
                ('rut', models.CharField(help_text='RUT del proveedor (sin puntos ni guion)', max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person', models.CharField(blank=True, help_text='Persona de contacto en el proveedor', max_length=255, null=True)),
                ('address', models.TextField(blank=True, help_text='Dirección del proveedor', null=True)),
                ('payment_terms', models.CharField(blank=True, help_text='Términos de pago (ej: Contado, 30 días, etc.)', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el proveedor está activo')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el proveedor', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Empresa propietaria del proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='catalyst_app.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(help_text='Proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='catalyst_app.supplier'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['company', 'is_active'], name='catalyst_ap_company_70eaaa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='catalyst_ap_role_a285ba_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['company'], name='catalyst_ap_company_d6b289_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='catalyst_ap_is_acti_f8b5fa_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['inventory', '-created_at'], name='catalyst_ap_invento_07a50c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type'], name='catalyst_ap_movemen_e3f2c6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', '-created_at'], name='catalyst_ap_company_3dd4db_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='catalyst_ap_status_f20b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='catalyst_ap_payment_6516ed_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'is_active'], name='catalyst_ap_company_d5d962_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='catalyst_ap_categor_15f2ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'sku')},
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['branch', 'product'], name='catalyst_ap_branch__8aec08_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['stock'], name='catalyst_ap_stock_23c35a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('branch', 'product')},
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['purchase'], name='catalyst_ap_purchas_16c801_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['branch', '-created_at'], name='catalyst_ap_branch__321dae_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['seller', '-created_at'], name='catalyst_ap_seller__beafa8_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-created_at'], name='catalyst_ap_created_ab72d4_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['user', 'company'], name='catalyst_ap_user_id_c18f59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['company', 'is_active'], name='catalyst_ap_company_30d4c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('company', 'rut')},
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier', '-purchase_date'], name='catalyst_ap_supplie_0b3e52_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['payment_status'], name='catalyst_ap_payment_a30a1a_idx'),
        ),
    ]
