# Generated by Django 5.2.8 on 2025-12-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('tarjeta', 'Tarjeta Crédito'), ('paypal', 'PayPal'), ('transferencia', 'Transferencia Bancaria'), ('prueba', 'Prueba Gratis')], default='prueba', help_text='Método de pago registrado del usuario', max_length=50, null=True),
        ),
    ]
